### ISSUE TITLE
[Question] Looping files

### ISSUE THREAD

**Issue by pruett** [mariusGundersen/gulp-forEach#8]
My knowledge of Node streams is little to none. That, plus gulp's async task runners has me running circles and I'm wondering if this gulp plugin is designed for what I'm looking for...

I'm looking to loop through files before proceeding to the next `.pipe()` call as I need to collect data from certain files before I can continue with the transformations. Is this what `gulp-foreach` is designed for?

Below is a snippet of an ugly gulp task I'm running in order to collect blog post meta data (in the form of frontmatter), create an object from that data and pass it along to my blog's index page. In order for this to work, I'll need to complete the full loop within the foreach statement.

```js
gulp.task('blog:index', function() {
  var templateData = require('../../src/data');
  var allPostsMeta = [];

  return gulp.src('./src/blog/views/posts/*')
    .pipe(foreach(function(stream, file) {
      gutil.log(file);
      return stream
        .pipe(data(function(file) {
          gutil.log('inside post metastream...');
          var fileName = path.basename(file.path, '.jade')
          var content = fm(String(file.contents));
          var postInfo = parseFileName(fileName);
          file.contents = new Buffer(content.body);
          var post = {
            meta: content.attributes,
            convertedDate: moment(postInfo.year+'-'+postInfo.month+'-'+postInfo.day).format('MMM Do, YYYY'),
            dirname: postInfo.year+'/'+postInfo.month+'/'+postInfo.day,
            basename: postInfo.post
          };
          allPostsMeta.push(post);
          gutil.log(allPostsMeta);
          templateData.posts = allPostsMeta;
        }))
    }))

    /*
    before I continue with the following transformations, 
    I need to run the above through completely!
    But it looks like the above only runs through one time
    */
    
    .pipe(addsrc('./src/blog/views/index.jade'))
    .pipe(jade({ locals: templateData, pretty: false }))
    .pipe(gulp.dest('./build/blog'))
    .pipe(connect.reload());
});
```

Any suggestions greatly appreciated. Thanks

**Comment by mariusGundersen** [comment]
You would need to buffer up the content of the stream right after the foreach for this to work. The reason gulp uses streams is to be memory efficient. If you read in 5 files (using `gulp.src`) then you could put all the content of those files in memory, or you could read one file at a time, send that single file through the stream all the way to the end (`gulp.dest`) and then read the next file. This way you only ever have one file in memory at a time. So the point of the stream interface is that you as a programmer don't have to worry about this, it looks like all files are in memory at the same time, but they might not be.

I would take a look at [through2](https://github.com/rvagg/through2), which behaves a little bit like foreach, but can be used for lots more. As I said, you need a buffer after the foreach step, so that none of the other steps happen before the stream ends. You could maybe get that to work with through2

**Comment by pruett** [comment]
thanks @mariusGundersen, i was able to solve my issue with through2. thanks!
